version: "3.3"
services:

  payments:
    image: keeonline/payments

  fandango:
    image: keeonline/fandango
    ports:
      - 8080:8080
    environment:
      MCBN_HOST: ${MCBN_HOST}
      PAYMENTS_BASE_URL: ${PAYMENTS_BASE_URL}
      # PAYMENTS_BASE_URL: http://payments:80
    depends_on:
      - payments
