version: "3.3"
services:

  # payments:
  #   image: keeonline/payments:latest
  #   ports:
  #     - 80:80

  fandango:
    image: keeonline/fandango:latest
    ports:
      - 8080:8080
    environment:
      MCBN_HOST: ${MCBN_HOST}
      PAYMENTS_BASE_URL: ${PAYMENTS_BASE_URL}
    # depends_on:
    #   - payments
