- name: Remove the environment working directory, if it exists
  ansible.builtin.file:
    path: '{{ mcbn_up_workdir }}/vtas-env'
    state: absent

- name: Ensure the working directory exists
  ansible.builtin.file:
    path: '{{ mcbn_up_workdir }}'
    state: directory

- name: Pull the Fandango GitHub repository
  ansible.builtin.git:
    repo: https://github.com/keeonline/vtas-env.git
    dest: '{{ mcbn_up_workdir }}/vtas-env'
    single_branch: yes
    version: '{{ mcbn_up_branch }}'
  environment:
      GIT_TERMINAL_PROMPT: 0
# TODO: add retry on pull ******************

# - name: Pause for 30 seconds so docker is started (to be replaced with wait_for)
#   ansible.builtin.pause:
#     seconds : 30

- name: Copy the MCBN VTAS environment into the VTAS env directory
  ansible.builtin.copy:
    src: '{{ mcbn_up_workdir }}/vtas-env/env/fandango_mcbn'
    dest: '{{ mcbn_up_vtas_env_dir }}'
    remote_src: true

- name: Start the MCBN VTAS environment
  ansible.builtin.uri:
    url: http://localhost:8084/restapi/CmdService/v1/envs/fandango_mcbn/start
    method: POST
  register: mcbn_up_result
  until: mcbn_up_result.status == 200
  retries: 36
  delay: 5


# - name: Remove the environment working directory
#   ansible.builtin.file:
#     path: '~/fandango/{{ fandango_up_env }}'
#     state: absent
