- name: Remove the environment working directory, if it exists
  ansible.builtin.file:
    path: '~/fandango/{{ fandango_up_env }}'
    state: absent

- name: Create the environment working directory
  ansible.builtin.file:
    path: '~/fandango/{{ fandango_up_env }}'
    state: directory

- name: Pull the Fandango GitHub repository
  ansible.builtin.git:
    repo: https://github.com/keeonline/fandango.git
    dest: '~/fandango/{{ fandango_up_env }}/fandango'
    single_branch: yes
    version: '{{ fandango_up_branch }}'
  environment:
      GIT_TERMINAL_PROMPT: 0
# TODO: add retry on pull ******************

- name: Start the application
  ansible.builtin.command:
    chdir: '~/fandango/{{ fandango_up_env }}/fandango'
    cmd: ls -lsa

- name: Wait for the docker-compose.yml file to be in situ
  ansible.builtin.wait_for:
    timeout: 60
    path: '~/fandango/{{ fandango_up_env }}/fandango/docker-compose.yml'
  
- name: Start the application
  ansible.builtin.command:
    chdir: '~/fandango/{{ fandango_up_env }}/fandango'
    cmd: docker-compose up -d

# - name: Remove the environment working directory
#   ansible.builtin.file:
#     path: '~/fandango/{{ fandango_up_env }}'
#     state: absent
