- name: Remove the environment working directory, if it exists
  ansible.builtin.file:
    path: '~/fandango/{{ fandango_up_env }}'
    state: absent

- name: Create the environment working directory
  ansible.builtin.file:
    path: '~/fandango/{{ fandango_up_env }}'
    state: directory

- name: Pull the Fandango GitHub repository
  ansible.builtin.git:
    repo: https://github.com/keeonline/fandango.git
    dest: '~/fandango/{{ fandango_up_env }}/fandango'
    single_branch: yes
    version: '{{ fandango_up_branch }}'
  environment:
      GIT_TERMINAL_PROMPT: 0

- name: Pause for 59 seconds so docker is started (to be replaced with wait_for)
  ansible.builtin.pause:
    seconds : 59

- name: Create the installation variable file
  ansible.builtin.template:
    src: .env.j2
    dest: '~/fandango/{{ fandango_up_env }}/fandango/.env'

- name: Start the application
  ansible.builtin.command:
    chdir: '~/fandango/{{ fandango_up_env }}/fandango'
    cmd: docker-compose up -d
