- name: Remove the environment working directory, if it exists
  ansible.builtin.file:
    path: '{{ vtas_up_workdir }}/vtas-env'
    state: absent

- name: Ensure the working directory exists
  ansible.builtin.file:
    path: '{{ vtas_up_workdir }}'
    state: directory

- name: Pull the Fandango GitHub repository
  ansible.builtin.git:
    repo: https://github.com/keeonline/vtas-env.git
    dest: '{{ vtas_up_workdir }}/vtas-env'
    single_branch: yes
    version: '{{ vtas_up_branch }}'
  environment:
      GIT_TERMINAL_PROMPT: 0

- name: Copy the fandango_mcbn VTAS environment into the VTAS env directory
  ansible.builtin.copy:
    src: '{{ vtas_up_workdir }}/vtas-env/env/fandango_mcbn'
    dest: '{{ vtas_up_vtas_env_dir }}'
    remote_src: true

- name: Start the fandango_mcbn VTAS environment
  ansible.builtin.uri:
    url: http://localhost:8084/restapi/CmdService/v1/envs/fandango_mcbn/start
    method: POST
  register: vtas_up_fandango_mcbn_result
  until: vtas_up_fandango_mcbn_result.status == 200
  retries: 10
  delay: 5

- name: Copy the fandango_api_rsp VTAS environment into the VTAS env directory
  ansible.builtin.copy:
    src: '{{ vtas_up_workdir }}/vtas-env/env/fandango_api_rsp'
    dest: '{{ vtas_up_vtas_env_dir }}'
    remote_src: true

- name: Start the fandango_api_rsp VTAS environment
  ansible.builtin.uri:
    url: http://localhost:8084/restapi/CmdService/v1/envs/fandango_api_rsp/start
    method: POST
  register: vtas_up_fandango_api_rsp_result
  until: vtas_up_fandango_api_rsp_result.status == 200
  retries: 10
  delay: 5
